---

- hosts: all
  become: true
  pre_tasks:


  - name: install update (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
  
- hosts: all
  become: true
  tasks:
    
    - name: create simone user
      tags: always
      user:
        name: simone
        groups: root  
       
    - name: add ssh key for simone
      tags: always
      authorized_key:
        user: simone
        key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFrLMeEYn7VkMSaLfsl4GzYZmGCDecfMc1DxdHOFBXXZ ansible"

    - name: add sudoers file for simone
      copy:
        src: sudoer_simone
        dest: /etc/sudoers.d/simone
        owner: root
        group: root
        mode: 0440

