---

- hosts: all
  become: true
  pre_tasks:


  - name: install update (Ubuntu)
    apt:
      upgrade: dist
      update_cache: yes

- hosts: web_servers
  become: true
  tasks:

  - name: install apache2 and php package
    package: 
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest

- hosts: db_servers
  become: true
  tasks:

    - name: install mariadb package
      apt:
        name: mariadb-server

- hosts: file_servers
  become: true
  tasks:

    - name: install samba package
      package:
        name: samba
        state: latest

