---

- hosts: all
  become: true
  pre_tasks:


  - name: install update (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes

- hosts: web_servers
  become: true
  tasks:

  - name: install apache2 and php package
    tags: apache2,php
    package: 
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
  
  - name: copy html file for site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644    

        
- hosts: db_servers
  become: true
  tasks:

    - name: install mariadb package
      tags: db, mariadb
      apt:
        name: mariadb-server

- hosts: file_servers
  become: true
  tasks:

    - name: install samba package
      tags: file_servers, samba
      package:
        name: samba
        state: latest

