---

- hosts: all
  become: true
  pre_tasks:


  - name: install update (Ubuntu)
    tags: always
    apt:
      update_cache: yes
    changed_when: false
  
- hosts: all
  become: true
  tasks:
    
    - name: create simone user
      tags: always
      user:
        name: simone
        groups: root  
       
    - name: add ssh key for simone
      tags: always
      authorized_key:
        user: simone
        key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFrLMeEYn7VkMSaLfsl4GzYZmGCDecfMc1DxdHOFBXXZ ansible"


- hosts: workstations
  become: true
  roles:
    - workstations

- hosts: web_servers
  become: true
  roles:
    - web_servers  

        
- hosts: db_servers
  become: true
  roles:
    - db_servers


- hosts: file_servers
  become: true
  roles:
    - file_servers


